### ISSUE TITLE
Remove user login features from backend

### ISSUE THREAD

**Issue by Syntaf** [CLTracker/CLT-webapp#2]
We will be writing our own in-house login component using Auth0, so we need to strip off the default login feature that came with Flask.

The server/models/etc should be cleaned up so the only route available is /api/getdata. All the user stuff needs to go.

**Comment by lilylei95** [comment]
I think I removed all the code that I think it was related to the flask default login and users. Not sure if I removed all of it or I deleted something that I wasn't suppose to delete.

**Comment by Syntaf** [comment]
Nice!  you should make a new branch and create a pull request so @stevenbrookslv can make sure you left the right stuff there. Here's how you'd do it from the cline:

Create a new branch called _fixes2_
`C:\....\CLT-webapp> git checkout -b fixes2`

Set the upstream to the remote repository and push changes
`C:\....\CLT-webapp> git push --set-upstream origin fixes2`

Then once you have the branch on the remote you can go to `Pull requests` and create a PR using the branch.

info: https://help.github.com/articles/creating-a-pull-request/

**Comment by stevenbrookslv** [comment]
Closing due to original problem at hand being handled
