### ISSUE TITLE
/login route must be refactored as accordance to #19

### ISSUE THREAD

**Issue by Syntaf** [CLTracker/CLT-webapp#21]
The `/login` route will be changed when #19 is implemented in order to handle multiple portals. The following should be changed: 

- A new flag will called `loginType` will be passed alongside the TOKEN to specify what portal the user is trying to login to

- If the user is attempting to login as an exhibitor:

  - Check `permitted_exhibitors` table of conference to see if user is allowed to login
  - If *yes* then we proceed as normal (add user if doesnt exist and return TOKEN regardless)
  - If *no* then return error for frontend to tell user they are not allowed access

- If the user is attempting to login as a conference organizer:

  - Check `organizers` table to see if user is allowed to login
  - If *yes* then we proceed as normal (add user if doesnt exist and return TOKEN regardless)
  - If *no* then return error for frontend to tell user they are not allowed access

**Comment by stevenbrookslv** [comment]
This was done with last commit I made. If upon review it seems like it isn't actually done, we can re-open the issue.
