### ISSUE TITLE
Ensure backend supports /news api

### ISSUE THREAD

**Issue by Syntaf** [CLTracker/CLT-webapp#31]
In order to support the proposed /news api, the following must be met:

- [x] news table which contains 3 fields for each entry:
  - **title**: string 
  - **logo**: string (url to logo)
  - **text**: string
- [x] GET news route created which returns JSON object containing list of news items

**Comment by stevenbrookslv** [comment]
Is this the same as schedule, or something different?

**Comment by Syntaf** [comment]
@stevenbrookslv This is different from a schedule. The news is what the user sees on the landing page of the app, the schedule is a view they can look at which gives a formal view of the conference.

An example of a news item might be 
```
{
  title: "Free donuts at CLT booth"
  logo: "imgur.com/xxxxx"
  text: "Donuts will be served at the CLT booth until 4PM today, drop by for a free one!"
}
```

**Comment by arjeem** [comment]
Added news table with fields "title", "logo_url", and "text" fields in commit f753f5633d3596fff54820b818ea3b178d25e71d.

Those are the only fields present in it currently. Should there be any more or is that workable?

**Comment by Syntaf** [comment]
@arjeem can't think of any other fields atm, so I think it should be good

**Comment by lilylei95** [comment]
Fixed /news to work with current database. Will close issue for now unless sometime comes up. Check the wiki page to see what you need to send.
