### ISSUE TITLE
Make flask also write log to console

### ISSUE THREAD

**Issue by Syntaf** [CLTracker/CLT-webapp#4]
Instead of the backend only writing to the log, we should also write to the console.

**Comment by stevenbrookslv** [comment]
We can write to the console by using
print(debug message)
during development. 

As far as running application logging, we can even use some logging library, or even the one in included

**Comment by stevenbrookslv** [comment]
I don't think there is anything to be done regarding this issue for the moment, until backend gets more complicated and perhaps a more complicated logging scheme is needed. Closing issue for now, we can reopen when needed
