### ISSUE TITLE
Write /user/exhibitors/:conf 

### ISSUE THREAD

**Issue by Syntaf** [CLTracker/CLT-webapp#43]
This route returns a list of all users for a conference that are exhibitors

[link](https://github.com/CLTracker/CLT-webapp/wiki/API-design#user-userexhibitorsconf)

**Comment by lilylei95** [comment]
Do you want it to return something like this:
`[ /* any # of: */ {  email: string, name: string, company: string } ]` 
instead of :  `{ email: string, name: string, company: string }` ?

**Comment by Syntaf** [comment]
@lilylei95 correct, let me correct the wiki. thanks!

**Comment by lilylei95** [comment]
@Syntaf Do want us to return a extra field like status to show if they are complete/incomplete? Something like this instead `[ /* any # of */ {email : string, name: string, company: string, status: "incomplete" or "complete"}]`

**Comment by Syntaf** [comment]
@lilylei95 that would be great if you'd like to add that as well, otherwise I was going to do that myself in the frontend. Either works for me.

**Comment by lilylei95** [comment]
written without status field
